config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only:[:new, :create, :destroy]
  resources :users, only:[:new, :create]
  root to: 'pictures#home'
  resources :pictures do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  validates :image, presence: true
  mount_uploader :image, ImageUploader
  validates :sentence, presence: true, length: {maximum:600}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pictures
  has_secure_password
  validates :name, presence: true, length: { minimum: 5, maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, presence: true, length: { minimum: 7 }                  
  before_validation { email.downcase! }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def authenticate_user
    if current_user.nil?
      flash[:notice] = 'ログインしてください'
      redirect_to new_session_path
    end
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_user, only: [:new, :edit, :home]

  def home
    redirect_to pictures_path
  end

  def index
    @pictures = Picture.all
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = current_user.pictures.build(picture_params)
    if params[:back] || @picture.invalid?
      render :new
    else
      @picture.save
      redirect_to picture_path(@picture.id)
    end
  end

  def edit
    @picture = Picture.find(params[:id])
  end

  def show
    @picture = Picture.find(params[:id])
  end

  def update
    @picture = Picture.find(params[:id])
    if @picture.update(picture_params)
      redirect_to picture_path(@picture.id)
    else
      render :edit
    end
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    redirect_to pictures_path

  end

  def confirm
    @picture = current_user.pictures.build(picture_params)
    render :new if @picture.invalid?
  end

  private
  def picture_params
    params.require(:picture).permit(:image, :image_cache, :sentence, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = 'loged in'
      redirect_to pictures_path
    else
      redirect_to new_session_path flash[:notice] = 'failed login'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to new_session_path flash[:notice] = 'loged out'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if User.find_by(email: params[:user][:email].downcase)
      flash.now[:notice] = '既に登録されているemailです。'
      render :new
    elsif @user.save
      session[:user_id] = @user.id
      redirect_to pictures_path
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error.html.erb
<% if cause.errors.any? %>
  <div id="error_explanation">
  <h2><%= pluralize(cause.errors.count, "error") %> prohibited this product from being saved:</h2>
  <ul>
    <% cause.errors.full_messages.each do |message| %>
      <li style="color: red;"><%= message %></li>
    <% end %>
  </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bacefook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-primary">
      <%= link_to "Facebook", pictures_path, class: "navbar-brand facebook_logo" %>
      <% if logged_in? %>
        <div>
          <%= link_to 'ログアウト', session_path(@current_user.id),
          method: :delete, class: "btn btn-success mr-sm-2" %>
          <%= link_to '新規投稿', new_picture_path, class: "btn btn-success my-2 my-sm-0" %>
          </div>
      <% else %>
        <div>
          <%= link_to 'ログイン', new_session_path, class: "btn btn-success mr-sm-2" %>
          <%= link_to '新規登録', new_user_path, class: "btn btn-success my-2 my-sm-0" %>
        </div>
      <% end %>
    </nav>
    <p style="color: red;"><%= flash[:notice] %></p>
    <%= yield %>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: @picture, local: true, url: new_or_edit) do |form| %>
  <div class="card">
    <% if @picture.id %>
    <h5 class="card-header row">
        <%= image_tag "default_user.png", class: "col-sm-2"%>
      <div class="col-sm-10">
        <p>hogehoge</p>
        <h4>投稿を編集する</h4>
      </div>
    </h5>
    <% else %>
    <h5 class="card-header row">
        <%= image_tag "default_user.png", class: "col-sm-2"%>
      <div class="col-sm-10">
        <p>hogehoge</p>
        <h4>新規投稿する</h4>
      </div>
    </h5>
    <% end %>
    <div class="card-body">
      <h3 class="card-title">あなたの投稿</h3>
      <h5 class="card-text"><%= form.label :image %></h5>
      <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
      <%= form.file_field :image %>
      <%= form.hidden_field :image_cache %>
      <h5 class="card-text"><%= form.label :sentence %></h5>
      <%= form.text_area :sentence, size: "40x6" %>
      <% if @picture.id %>
        <input type="submit" name="commit" value="保存する"
        class="btn btn-success" />
      <% else %>
      <div class="submit_btn_container">
        <input type="submit" name="commit" value="投稿する"
        class="btn btn-success" />
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/pictures/confirm.html.erb
<%= form_with(model: @picture, local: true) do |form| %>
  <div class="card">
    <h5 class="card-header alert alert-primary" role="alert">この内容で投稿してもいいですか？</h5>
    <div class="card-body">
      <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
      <%= form.hidden_field :image_cache %>
      <br>
      <%= form.hidden_field :sentence %>
      <h5 class="card-text"><%= form.label :sentence %></h5>
      <%= form.text_area :sentence, size: "40x6" %>
      <div class="submit_btn_container">
      <input type="submit" name="commit" value="投稿" data-disable-with="Create User"
      class="btn btn-success hoge" />
      <input type="submit" name="back" value="戻る" data-disable-with="Create User"
      class="btn btn-success"/>
      </div>
    </div>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<%= render 'layouts/error', cause: @picture %>
<%= render 'form' %>

app/views/pictures/index.html.erb
<% @pictures.each do |p| %>
  <div class="picture_container">
    <h5>投稿</h5>
    <div class="user_field">
      <%= image_tag "default_user.png", class: "user_image", size: "40x40" %>
      <span><%= p.user.name %></span>
    </div>
    <p><%= p.sentence %></p>
    <%= image_tag p.image.url, class: "posted_picture" %>
    <%= link_to '詳細ページへ', picture_path(p.id) %>
  </div>
<% end %>

app/views/pictures/new.html.erb
<%= render 'layouts/error', cause: @picture %>
<%= render 'form' %>

app/views/pictures/show.html.erb
<div class="container">
<div class="media row">
  <%= image_tag @picture.image.url, class: "col-sm-7" %>
  <div class="media-body col-sm-5">
    <h5 class="mt-0">
      <%= image_tag "default_user.png", class: "user_image", size: "40x40" %>
      <%= @picture.user.name %>
    </h5>
      <p><%= @picture.sentence %></p>
      <%= link_to 'edit', edit_picture_path(@picture.id) %>
      <%= link_to 'delete', picture_path(@picture.id), method: :delete %>
  </div>
</div>
</div>

app/views/users/new.html.erb
<%= form_with(model: @user, local: true) do |form| %>
  <%= render 'layouts/error', cause: @user %>
  <div class="card">
  <h5 class="card-header">アカウント登録</h5>
  <div class="card-body">
    <h5 class="card-text"><%= form.label :name %></h5>
    <div class="hoge"><%= form.text_field :name %></div>
    <h5 class="card-text"><%= form.label :email %></h5>
    <%= form.text_field :email %>
    <h5 class="card-text"><%= form.label :password%></h5>
    <%= form.password_field :password %>
    <h5 class="card-text">  <%= form.label :password_confirmation %></h5>
    <%= form.password_field :password_confirmation %>
    <div class="submit_btn_container">
      <input type="submit" name="commit" value="アカウント登録" data-disable-with="Create User"
      class="btn btn-success" />
    </div>
  </div>
</div>
<% end %>